version: '3.6'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: ${CALLS_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        networks:
        - backend

    query-service:
      build: ./query-service
      depends_on:
        - db
      container_name: query-service
      ports:
        - ${QUERY_SERVICE_PORT}:${QUERY_SERVICE_PORT}
      expose:
        - ${QUERY_SERVICE_PORT}
      restart: always
      links:
        - db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${POSTGRES_PORT}/${CALLS_DB}
        - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
        - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      networks:
        - backend
        - frontend

    app:
      build: ./app
      container_name: app
      restart: always
      environment:
        - QUERY_SERVICE_PORT=${QUERY_SERVICE_PORT}
        - QUERY_SERVICE_HOST=http://query-service
      ports:
        - ${APP_SERVICE_PORT}:${APP_SERVICE_PORT}
      links:
        - query-service  
      networks:
        - frontend
networks:
  backend:
  frontend: