version: '3.6'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: calls
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password  
        networks:
        - backend

    query-service:
      build: ./query-service
      depends_on:
        - db
      container_name: query-service
      ports:
        - 8002:8002
      expose:
        - 8002
      restart: always
      links:
        - db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/calls
        - SPRING_DATASOURCE_USERNAME=user
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      networks:
        - backend
        - frontend

    app:
      build: ./app
      container_name: app
      restart: always
      ports:
        - 8001:8001
      links:
        - query-service  
      networks:
        - frontend
networks:
  backend:
  frontend: